plugin: aws_ec2

#aws_access_key: AKIATL2YPMWWT4BMQWRU
#aws_secret_key: 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

regions:
  - us-east-1

filters:
  instance-state-name : running
 
keyed_groups:
  - key: tags.Name
    prefix: ""
    separator: ""

hostnames:
  - private-ip-address

compose:
  ansible_host: private_ip_addressp
